<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sql</string>
		<string>ddl</string>
		<string>dml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*(begin|if|loop)\b</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*(end)\b</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>PL/SQL (Oracle)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.line.double-dash.oracle</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(create)(\s+or\s+replace)?\s+</string>
			<key>name</key>
			<string>meta.create.oracle</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.oracle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(package)(\s+body)?\s+(\S+)</string>
			<key>name</key>
			<string>meta.package.oracle</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.oracle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(type)\s+"([^"]+)"</string>
			<key>name</key>
			<string>meta.type.oracle</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.oracle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.oracle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(function|procedure)\s+([-a-z0-9_]+)</string>
			<key>name</key>
			<string>meta.procedure.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[!&lt;&gt;:]?=|&lt;&gt;|&lt;|&gt;|\+|(?&lt;!\.)\*|-|(?&lt;!^)/|\|\|</string>
			<key>name</key>
			<string>keyword.operator.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(if|elsif|else|end\s+if|loop|end\s+loop|for|case|end\s+case|continue|return|goto)\b</string>
			<key>name</key>
			<string>keyword.control.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(or|and|not|like)\b</string>
			<key>name</key>
			<string>keyword.operator.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(sysdate|%(isopen|found|notfound|rowcount)|commit|rollback|sqlerrm|substr|cast|decode|length|lower|upper)\b</string>
			<key>name</key>
			<string>support.function.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(avg|count|sum|max|min|nvl|trim|to_date|to_char|lpad|ltrim|rpad|rtrim|trunc|to_number)\b</string>
			<key>name</key>
			<string>support.function.builtin.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(sql|sqlcode)\b</string>
			<key>name</key>
			<string>variable.language.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(p(i|o|io)_[-a-z0-9_]+)\b</string>
			<key>name</key>
			<string>variable.parameter.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(l_[-a-z0-9_]+)\b</string>
			<key>name</key>
			<string>variable.other.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(end|then|exception|when|others|begin|in|out|is|as|exit|open|fetch|into|close|type|rowtype|default|\.(extend|count|first|last|next|nextval|currval))\b</string>
			<key>name</key>
			<string>keyword.other.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(select|from|where|order\s+by|group\s+by|asc|desc|update|set|insert|into|values|delete|from|distinct|union|having|limit|table|of)\b</string>
			<key>name</key>
			<string>keyword.other.sql.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(dbms_lock|dbms_output)\b</string>
			<key>name</key>
			<string>support.class.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(put_line)\b</string>
			<key>name</key>
			<string>support.function.oracle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.oracle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.oracle</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(number|integer|varchar2|boolean|date)\b</string>
			<key>name</key>
			<string>storage.type.oracle</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.plsql.oracle</string>
	<key>uuid</key>
	<string>28DCE4DD-F5E1-4ED3-8847-64DA6B1F9163</string>
</dict>
</plist>
